language: ruby
rvm:
- 2.6.4
branches:
  only:
  - master
before_script:
- echo $DOCKER_TOKEN | docker login -u $DOCKER_NAMESPACE  --password-stdin
script:
- IMAGE_TAG=latest make auto_build
notifications:
  email: false
  slack:
    secure: iISuUY2+k9vJizGRnmItAsCb+mADD0l4r7wTxJ87jnLjG1V2g9KqOtksn0GnMUKH6V4QEUpOhi6yOnalU7FH2AZ1X1gK6YfQQktgaXrXUJuIlDXc8Xz+77FTthlrsOCUqRcnmy23aIiHnEYl5jCljUa+nz6pzl0TJSTc4XiUObStsdCEj9f+Gw7Oi7ZivpfS0Yg4opkA0vKku8KUOk0Ck2k0VCjEK0N0OLbp3M2oX1CbeS9flRjG2TROI3KyA23oOo+zXkUeqB6+6UIXZU8XUPfwIV/JukrlLlipiM0N03Jxbtfrq2DZf9peS8HbCXRUyTkeB/lEivtDtqxxZPMkZHd0Q0SE+IAXVuE7mEod/qTePbLqKDhBizHXoVkq6jChYt/qcqYGGOw7f2M6FhFwe0BfeQsiUkpl5C80gJBIpWJImKXO2ch9LlCCEqsjrBKRvxByULacwXZUi1ZCy7jWoum40OEmL8f4KV+HmxgKW28+GLuFGNpGzqsdKGfu3yAX4MAUc8aczs1z5ra4nok9QlxnAJxN+mw+84Cf4mLQlQKqwUWWV7ldvhsDBSxRL/b5brx0qie8ShCGjCC/MhOMb6A1cs79iTugMyuxXXwnz3fbQ+OsYp8DGgj/1vnRZvItINgEL5R1rBlqEaLnxKeBbAIBnZyKjVn1ZMQh4tKQ1/I=
